spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  rabbitmq:
    addresses: 192.168.1.100
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
  # mapper.xml的位置
  mapper-locations: classpath:mapper/*.xml

# 开启SQL日志
logging:
    level:
      com.lyj.pay.dao: debug

# 微信支付参数
wxpay:
  appId:
  mchId:
  mchKey:
  notifyUrl:
  returnUrl:
# 支付宝参数
alipay:
  appId:
  privateKey:
  publicKey:
  notifyUrl:
  returnUrl:
